
CREATE TABLE attachment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    attachment_url VARCHAR(255),
    CONSTRAINT pk_attachment PRIMARY KEY (id)
);

CREATE TABLE comment
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id   BIGINT,
    user_id   BIGINT                                  NOT NULL,
    body      VARCHAR(255),
    date      date                                    NOT NULL,
    parent_id BIGINT,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE post
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text          VARCHAR(255),
    user_id       BIGINT,
    date          date                                    NOT NULL,
    attachment_id BIGINT,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(30),
    last_name  VARCHAR(30),
    username   VARCHAR(30),
    email      VARCHAR(30),
    password   VARCHAR(255),
    bio        VARCHAR(1000),
    role       VARCHAR(255),
    photo      VARCHAR(1000),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_ATTACHMENT FOREIGN KEY (attachment_id) REFERENCES attachment (id);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);